### ISSUE TITLE
盈亏比公式变更

### ISSUE THREAD

**Issue by ArcDemon** [lostsquirrel/futures-collector#10]
总体盈亏比= （（总体盈利额 - 总体盈利交易手续费）/总盈利次数）/（（总体亏损额绝对值+总体亏损交易手续费）/ 总亏损次数）x 100%
5交易日盈亏比= （（5交易日盈利额 - 5交易日盈利交易手续费）/5交易日盈利次数）/（（5交易日亏损额绝对值+5交易日亏损交易手续费）/ 5交易日亏损次数）x 100%

**Comment by lostsquirrel** [comment]
总体盈亏比= （总体盈利额/总盈利次数）/（（总体亏损额/ 总亏损次数+总体手续费/(总盈利次数+总亏损次数)））x 100%
盈利和亏损都有手续费，也要平均到每次吧
